const breadcrumbMap = {
  // Extra
  "extra/art practice": "art_practice.html",
  "extra/art practice/cgi": "cgi.html",
  "extra/art practice/cgi/ssa": "ssa.html",
  "extra/art practice/cgi/ssa2": "ssa2.html",
  "extra/art practice/installations": "installations.html",
  "extra/art practice/photoseries": "photoseries.html",
  "extra/art practice/photoseries/autoportrait": "autoportrait.html",
  "extra/art practice/photoseries/londonhello": "londonhello.html",
  "extra/art practice/photoseries/orthofuture": "orthofuture.html",
  "extra/art practice/photoseries/pacanbalet": "pacanbalet.html",
  "extra/art practice/photoseries/portraits": "portraits.html",
  "extra/art practice/photoseries/unreal": "unreal.html",
  "extra/art practice/uarchive": "uarchive.html",
  "extra/art practice/uarchive/uarchive2": "uarchive2.html",
  "extra/art practice/uarchive/uarchive3": "uarchive3.html",
  "extra/exhibitions": "exhibitions.html",
  "extra/live events": "live_events.html",
  "extra/live events/la1": "la1.html",
  "extra/performances": "performances.html",
  "extra/performances/meatpacking_biennale": "meatpacking_biennale.html",
  "extra/art_practice": "art_practice.html",
  "extra/brief_history": "brief_history.html",
  "extra/exhibitions": "exhibitions.html",
  "extra/live_events": "live_events.html",
  "extra/performances": "performances.html",
  "extra/videoart": "videoart.html",

  // Nav
  "nav/about": "about.html",
  "nav/contact": "contact.html",

  // Projects
  "projects": "all.html",
  "projects/animation": "animation.html",
  "projects/animation/daly_syndrome": "daly_syndrome.html",
  "projects/animation/ewp_project": "html/projects/animation/ewp_project.html",
  "projects/audio": "audio.html",
  "projects/audio/eli/epeorgaanistenrakenteidekierratys": "epeorgaanistenrakenteidekierratys.html",
  "projects/audio/eli/lab_anouncement_3.html": "lab_anouncement_3.html",
  "projects/audio/geztalt": "gez_interview.html",
  "projects/audio/tanerlach": "tanerlach.html",
  "projects/audio/eli": "eli.html",
  "projects/audio/geztalt": "geztalt.html",
  "projects/collaborations": "collaborations.html",
  "projects/collaborations/sasha_e__b": "sasha_e__b.html",
  "projects/collaborations/e6/Lupen": "Lupen.html",
  "projects/collaborations/e6/zadek": "zadek.html",
  "projects/collaborations/anna_mikhaylova": "anna_mikhaylova.html",
  "projects/collaborations/asya_melnikova": "asya_melnikova.html",
  "projects/collaborations/georgiy_orlov_davydovsky": "georgiy_orlov_davydovsky.html",
  "projects/collaborations/igor_yanovsky": "igor_yanovsky.html",
  "projects/collaborations/julia_baranyuk": "julia_baranyuk.html",
  "projects/collaborations/marysia_izdebska": "marysia_izdebska.html",
  "projects/collaborations/oleg_makarov": "oleg_makarov.html",
  "projects/collaborations/romaner": "romaner.html",
  "projects/collaborations/spalah": "nipagana.html",
  "projects/collaborations/dynakyris": "dynakyris.html",
  "projects/collaborations/varvara_kuleshova": "varvara_kuleshova.html",
  "projects/games": "games.html",
  "projects/games/desodissey": "desodissey.html",
  "projects/games/elysium": "elysium.html",
  "projects/games/metaliminal": "metaliminal.html",
  "projects/games/nightmafia": "nightmafia.html",
  "projects/games/outsider": "outsider.html",
  "projects/games/sleepdom": "sleepdom.html",
  "projects/interactive": "interactive.html",
  "projects/interactive/belial": "belial.html",

  // Work in Progress
  "workinprogress": "workinprogress.html"
};
